### ISSUE TITLE
Schedule config to run clockin or clockout

### ISSUE THREAD

**Issue by k1m0ch1** [ans-4175/talenta-api#8]
using `pm2` or create a custom script, do whatever you like, the only goal is "user can run this program with schedule with custom coordinate" so it will be automated.

@ans-4175 can you set labels `hacktoberfest`

**Comment by yuhanasy** [comment]
I'm going to work on this. With @k1m0ch1 suggestions, I will use pm2 to run scheduler. 
I propose for now, that user need to add 
```
{
  timeClockIn: "hh:mm",
  timeClockOut: "hh:mm",
}
```
in `config.js`.

**Comment by yuhanasy** [comment]
and can you assign this issue to me?

**Comment by k1m0ch1** [comment]
issue asignee is only available for contributor, so made your first PR with this issue, it will automatically asigned to the first PR in this issue.

goos luck

**Comment by ans-4175** [comment]
>  I will use pm2 to run scheduler

So if you are using PM2, then config.js.tmpl would be edited and README also expected need to be refined.
Let's see your solution.

> and can you assign this issue to me?

Sure, assigned. Non contributor also can be assigned, after commented issues

**Comment by ans-4175** [comment]
@yuhanasy you could elaborate your design flow/code first

**Comment by yuhanasy** [comment]
@ans-4175  I've already submitted a draft PR. You may check my code, while I'm going to update related documentation. 
Give me feedback if there need some improvements within that PR. Or maybe on separate PR.
